### ISSUE TITLE
全部代码全新下载，有很多代码重复了，合并出错了？

### ISSUE THREAD

**Issue by cicna** [52ABP/MPACore.PhoneBook#1]
无法生成，有很多处代码重复了

**Comment by HillCat** [comment]
git clone  , linux压缩之后有200多M。

**Comment by ltm0203** [comment]
ok。我检查下内容。

**Comment by ltm0203** [comment]
![image](https://user-images.githubusercontent.com/7875527/44920403-68260800-ad72-11e8-82cf-6c275d31e66d.png)
我直接clone下来的也只有。。。39MB 啊。。   @HillCat 你的这个。。。200mb是怎么来的啊。。。

**Comment by HillCat** [comment]
![2018-08-31_230913](https://user-images.githubusercontent.com/41800196/44920617-fef2c480-ad72-11e8-8e02-0173272ac26c.jpg)

**Comment by ltm0203** [comment]
你这个。。。。。哎。。。
你要编译啊。。哪里有直接把源代码存Linux的啊。。。

**Comment by HillCat** [comment]
姿势搞错了。用的wget.     ::>_<::
