### ISSUE TITLE
生成不了数据库

### ISSUE THREAD

**Issue by ZhenQiangS** [52ABP/MPACore.PhoneBook#2]
都按照你说的注意事项做了，就是生成不了数据库

**Comment by ltm0203** [comment]
![image](https://user-images.githubusercontent.com/7875527/44920500-ade2d080-ad72-11e8-86b5-9f35e0e25dbe.png)
先记得在自己本地安装数据库 sqlserver2014（推荐），不要低于2012否则会有bug
然后，选择`MPACore.PhoneBook.Web.Mvc` 为你的启动项
然后进行如图配置
![image](https://user-images.githubusercontent.com/7875527/44920574-e387b980-ad72-11e8-8d6e-254afd9ccdbd.png)

然后执行`update-database`。
![image](https://user-images.githubusercontent.com/7875527/44920638-0b771d00-ad73-11e8-8edd-6a64664b2566.png)
最后执行成功。
