### ISSUE TITLE
有关智能提示的疑问

### ISSUE THREAD

**Issue by ystemni** [52ABP/MPACore.PhoneBook#3]
请问：视频中的智能提示，可以从当前解决方案中命名空间查找（见图11）
![11](https://user-images.githubusercontent.com/16860072/40153214-4b00aa6a-59bb-11e8-89c6-73701719f5e4.png)

我的VS2017，只能从当前文档已经using的命名空间查找（见图22）
![22](https://user-images.githubusercontent.com/16860072/40153215-4b44dd02-59bb-11e8-85ab-f7181f26db66.png)

请问是如何设置的？或者缺少了什么插件？

**Comment by ltm0203** [comment]
resharper 插件你可以安装下

**Comment by ystemni** [comment]
谢谢！
